### ISSUE TITLE
Can not parse this page...

### ISSUE THREAD

**Issue by jdrizzydrake** [hujinglin/MVA-Downloader#4]
![image](https://cloud.githubusercontent.com/assets/20068232/16231906/a4ea8fbc-37c8-11e6-88d4-247f05cfc2b9.png)

**Comment by jareddrake** [comment]
This is what I've been trying to search today. 

The URL is https://mva.microsoft.com/en-US/training-courses/system-center-2012-r2-configuration-manager-windows-intune-8254?l=fCzIjVKy_6404984382

Thanks

**Comment by jareddrake** [comment]
Just in case if you would like to know what I did install ... here is the below screenshot and see if it helps on resolving this matter ? 

![image](https://cloud.githubusercontent.com/assets/20068232/16232039/35dac3f2-37c9-11e6-990d-52b480a38c33.png)

**Comment by Abdullah2993** [comment]
works fine.
![here](http://i.imgur.com/zzcOMMh.png)

**Comment by hujinglin** [comment]
@jdrizzydrake Have you pulled the newest code and installed the node_modules ? I tried your link is fine too.

**Comment by jdrizzydrake** [comment]
Hello, thank you for your quick response, I'm not sure if I can follow up, how to install the node_modules ? Do i need to update the NodeJS version ?

**Comment by jdrizzydrake** [comment]
@hujinglin Now I cannot install, what's the problem with this ? 

![image](https://cloud.githubusercontent.com/assets/20068232/16263427/9a22cfca-3874-11e6-9ae5-3ba9c9b9883b.png)

**Comment by jdrizzydrake** [comment]
@hujinglin - I tried everything but still the same error.. See below:

![image](https://cloud.githubusercontent.com/assets/20068232/16263669/ee122b66-3875-11e6-9190-b9176b64e52e.png)

**Comment by jdrizzydrake** [comment]
@hujinglin Good news! It's working!

I just downloaded & installed the latest version of Node.js (recommend after Node.js version 0.12.0)

Here is the screenshot below:

![image](https://cloud.githubusercontent.com/assets/20068232/16264043/809f3360-3877-11e6-8c65-c0e1ee68c47b.png)

Thank you very much for your assistance :+1: 

Regards

**Comment by hujinglin** [comment]
@jdrizzydrake Congratulations 👍
